### ISSUE TITLE
science pack fails to install on a mac

### ISSUE THREAD

**Issue by prabhu** [AppThreat/chen#7]
```
chen --download
ERROR: Could not find a version that satisfies the requirement pyg-lib==0.2.0+pt20cu118 (from versions: none)
ERROR: No matching distribution found for pyg-lib==0.2.0+pt20cu118
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/bin/chen", line 8, in <module>
    sys.exit(main())
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/chenpy/cli.py", line 177, in main
    download_chen_distribution(args.download)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/chenpy/cli.py", line 153, in download_chen_distribution
    install_science_modules()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/chenpy/cli.py", line 164, in install_science_modules
    subprocess.check_call(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/3.9/bin/python3.9', '-m', 'pip', 'install', '-r', '/Users/prabhu/Library/Application Support/chen/chen-science-requirements.txt']' returned non-zero exit status 1.
```

**Comment by prabhu** [comment]
conda based installer is working on both mac and windows.
