### ISSUE TITLE
poetry install issue on windows

### ISSUE THREAD

**Issue by prabhu** [AppThreat/chen#8]
```
Collecting uvloop<0.18.0,>=0.17.0 (from appthreat-chen)
  Downloading uvloop-0.17.0.tar.gz (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 2.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "C:\Users\prabhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\prabhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\prabhu\AppData\Local\Programs\Python\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\prabhu\AppData\Local\Temp\pip-build-env-kr6yxyu5\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\prabhu\AppData\Local\Temp\pip-build-env-kr6yxyu5\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\prabhu\AppData\Local\Temp\pip-build-env-kr6yxyu5\overlay\Lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
          super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
        File "C:\Users\prabhu\AppData\Local\Temp\pip-build-env-kr6yxyu5\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 8, in <module>
      RuntimeError: uvloop does not support Windows at the moment
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by prabhu** [comment]
@cerrussell, I have made some improvements to make the project install on windows. But could you also take a look at your convenience?

**Comment by cerrussell** [comment]
[This workflow](https://github.com/AppThreat/chen/blob/fix/win_compat/.github/workflows/win_compat.yml) might be helpful for testing the Windows install...
Here's a [run](https://github.com/cerrussell/chen/actions/runs/6489773888/workflow) on my fork. As you can see, the poetry install runs ok, but chen --download and chen --download --with-science have some issues.

As of now, python 3.8 - 3.10 are able to do chen --download while 3.11 and 3.12 cannot as they can't build a wheel for rocksdb-py.

Chen --download --with-science doesn't work on any of the versions due to not being able to build a wheel for pygraphviz.

**Comment by prabhu** [comment]
Try the new conda-based installer which is working reliably.
